### ISSUE TITLE
Is there way to disable launching on startup?

### ISSUE THREAD

**Issue by code-IM-perfect** [NicoVarg99/MEGA-Instances#13]
First of all, thank you for this awesome tool, but ever since I set it up, the instances auto-launch on startup, which is not really necessary and I'd like to reduce my startup load.

**Comment by NicoVarg99** [comment]
To disable autostart, remove `~/.config/autostart/mega_instances.desktop`

edit: I have now updated the script, as it used to unnecessarily re-create the desktop entry at every execution.

**Comment by code-IM-perfect** [comment]
Thanks a lot
