### ISSUE TITLE
Getting GtkDialog error.

### ISSUE THREAD

**Issue by ajayexpert** [NicoVarg99/MEGA-Instances#3]
Every time that dialog pop up comes it shows this error : `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.` in terminal

How this happen?
if we create 2 instance then it is work like this.

`REALHOME = /home/<username>`
`MEGA-Instances is not configured. Will now start the configuration.`
then show this dialog
`How many MEGA instances do you need?`
Input : 2

In terminal
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged`

Dialog
`Insert the name for instance 1/2`
Input : dir1

In terminal
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged`

Dialog
`Insert the name for instance 2/2`
Input : dir2

In terminal
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged`

Dialog
`Instance dir1 (1/2). Close it after the configuration.`
Then it show the megasync dialog in so i put the login after configuration i close it then it is not working. now it is not asking second login config.

In terminal
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged`

**Comment by NicoVarg99** [comment]
This is Zenity's fault, not mine.
