### ISSUE TITLE
Script is not autostarting in Linux Mint

### ISSUE THREAD

**Issue by emailforos** [NicoVarg99/MEGA-Instances#5]
Hi.

I tried your useful script but it only works when executed manually. It doesn't run when login in my PC.

I'm not an experienced user/programmer so I don't know how to solve it. Maybe you can guide me to the solution.

Thank you for your help and work

**Comment by emailforos** [comment]
1. result:
[Desktop Entry]
Type=Application
Exec=/home/javier/MEGA/mega_instances.sh
Name=megasync_instances
Comment=Open all your MEGA instances

2. result:
-rwxrwxr-x 1 javier javier 135 nov  1 13:09 /home/javier/.config/autostart/mega_instances.desktop

Hope this help.

Thank you.

**Comment by emailforos** [comment]
Hi.

I finally found out what it was happening.

1. mega_instances.sh was installed in /home/javier/ so I copied it to /home/javier/MEGA/
2. mega_instances.sh hasn't permission for being executed so I change it.

It works.

**Comment by NicoVarg99** [comment]
The script in the current version  ([1c77dfe](https://github.com/NicoVarg99/MEGA-Instances/commit/1c77dfe1ffdac9d5030411447404b22260a98192)) should automatically copy itself to /home/user/MEGA/ and set the execution permission.
Do you confirm it didn't do it?

**Comment by emailforos** [comment]
Yes. I confirm it.

I followed your instructions in the readme (today), I opened a terminal I wrote: wget https://raw.githubusercontent.com/NicoVarg99/MEGA-Instances/master/mega_instances.sh && bash mega_instances.sh 

And it started the installation.

So when I restarted the system I found out that it doesn't auto execute the script. 

Maybe it was because my other problem (https://github.com/NicoVarg99/MEGA-Instances/issues/6) that I was not able to finish my two instances set up. So maybe it hasn't reached the end of the script file.

I'm not a programmer so... But maybe if you copy the file from the current directory to the MEGA directory at the first beginning of the script some other user (newbie like me), won't have this problem.

Thank you for your help and work.

**Comment by NicoVarg99** [comment]
Please try the new version (note: new installation instructions) and see if it is still not working.
The program gets now installed globally in /usr/bin.
Don't mind the old autostart/config files. They will get overwritten by the new version.

**Comment by emailforos** [comment]
Great job!

It worked like a charm.

Thank you very much.
